application: travel-app-fyp
version: 1
runtime: python
api_version: 1

handlers:   
- url: /stylesheet
  static_dir: stylesheet
  
- url: /images
  static_dir: images
  
- url: /admin
  login: admin
  script: travel_app.py
  
- url: /mobile/(.*\.appcache)
  static_files: mobile/\1
  mime_type: text/cache-manifest
  upload: mobile/(.*\.appcache)
  
- url: /mobile
  static_dir: mobile
  
- url: /.*
  login: required
  script: travel_app.py
  
threadsafe: true


