application: travel-app-fyp
version: 1
runtime: python
api_version: 1

handlers:
- url: /.*
  login: required
  script: travel_app.py
   
- url: /stylesheets
  static_dir: stylesheets
  
- url: /lib
  static_dir: lib
  
threadsafe: true

